name: example-environment

dependencies:
  - python=3.11.0-alpha.3
  - pip:
    - pymysql
    - pandas
    - jpype1
    - requests
    - nltk
    - tomotopy
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
